resolver: ghc-8.0.2
system-ghc: true
skip-ghc-check: true
ghc-options:
  postgrest: -O2 -Wall -fwarn-identities -fno-warn-redundant-constraints
packages:
- '.'
nix:
  enable: false
  packages: [postgresql, zlib]
